#!/usr/bin/env python3
import click

from deepsurf.framex import SurfFrames


@click.command()
@click.option("-i", "--interval", help="Duration between frame extractions", default=60)
@click.option("-o", "--out_path", help="Path to store frames.", required=True)
def main(interval, out_path):
    sf = SurfFrames(interval, out_path)
    sf.get_frames()


if __name__ == "__main__":
    main()
