#!/usr/bin/env python3
import click

from deepsurf.framex import SurfFrames


@click.command()
@click.option("-i", "--interval", help="Duration between frame extractions", default=60)
@click.option("-o", "--out_path", help="Path to store frames.", required=True)
@click.option("-l", "--logging", help="Set the logging level", default="loud")
def main(interval, out_path, logging):
    """Cli tool enabling easy collection of web cam data by downloading web cam data from scheveningenlive.nl

    Example usage:
        framex -i 40 -o /Path/to/deep-surf-data -l silent
    """
    sf = SurfFrames(interval, out_path, logging)
    sf.get_frames()


if __name__ == "__main__":
    main()
